/** English prose rules and length limits. Limits are estimates derived from the Korean bundle. */

/** Detect English after removing code spans. Require a Latin-character ratio of at least 0.7. */
export const script = {
  test: /[A-Za-z]/g,
  against: /[가-힣]/g,
  minRatio: 0.7,
  /** Short documents swing too much to judge. */
  minChars: 200,
  name: 'English',
}

/** Use a final period as a heuristic for a complete acceptance criterion. */
export const acSentence = /\.$/

/** Flag vague measurements using word boundaries. Lines containing numbers are exempt. */
export const vague = [
  /\bfast(er)?\b/i, /\bquick(ly)?\b/i, /\bslow\b/i, /\bappropriate(ly)?\b/i, /\bproper(ly)?\b/i,
  /\beas(y|ily)\b/i, /\bsimple\b/i, /\bseamless(ly)?\b/i, /\brobust\b/i, /\bscalable\b/i,
  /\bflexible\b/i, /\befficient(ly)?\b/i, /\boptimiz(e|ed|ation)\b/i, /\bimprove[ds]?\b/i,
  /\bbetter\b/i, /\benhance[ds]?\b/i, /\bstable\b/i, /\breliable\b/i, /\buser-friendly\b/i,
  /\bintuitive\b/i, /\bclean(er)?\b/i, /\bworks well\b/i, /\bno issues\b/i, /\bsufficient(ly)?\b/i,
  /\bmost of\b/i, /\boften\b/i, /\bas much as possible\b/i, /\bif possible\b/i, /\bsmooth(ly)?\b/i,
  /\band so on\b/i, /\betc\b/i,
]

/** Flag wordiness and passive constructions. */
export const translationese = [
  [/\bis\s+\w+ed\s+by\b/i, 'name the actor — «is processed by A» → «A processes»'],
  [/\bare\s+\w+ed\s+by\b/i, 'name the actor'],
  [/\bin order to\b/i, '«to»'],
  [/\bdue to the fact that\b/i, '«because»'],
  [/\bin the event that\b/i, '«if»'],
  [/\bfor the purpose of\b/i, '«to»'],
  [/\bat this point in time\b/i, '«now»'],
  [/\bhas the ability to\b/i, '«can»'],
  [/\bis able to\b/i, '«can»'],
  [/\bmake use of\b/i, '«use»'],
  [/\butilize[sd]?\b/i, '«use»'],
  [/\bprovides? (the )?(ability|functionality|support|capability)\b/i, 'say what it does — «provides the ability to search» → «searches»'],
  [/\bperforms? (a|an|the)\b/i, 'use the verb — «performs a check» → «checks»'],
  [/\bwith (regard|respect) to\b/i, '«about»'],
  [/\bit should be noted that\b/i, 'drop it — the sentence is the note'],
]

/** Sentences about the document instead of its subject. */
export const meta = [
  [/\bthis (document|section) (describes|explains|covers|outlines|introduces|defines)\b/i,
   'the document is describing itself. Write the content'],
  [/\bthe present document\b/i, '«this document» is usually unnecessary too'],
  [/\b(as (mentioned|described|noted) (above|earlier)|in the (next|following) section|below,? we)\b/i,
   'do not narrate the order — the headings already do that'],
  [/\bfor reference,/i, 'if it belongs in the body, write it; otherwise drop it'],
]

/** Light-tier character limits exclude whitespace. Estimate each limit as the Korean value × 2.2,
 * based on parallel README sections. Recalibrate with representative English artifacts. */
export const budget = {
  intent: { doc: 2600, section: 1100, entity: 550 },
  spec: { doc: 4400, section: 1800, entity: 880 },
  plan: { doc: 6600, section: 2600, entity: 770 },
  finding: { doc: 4400, section: 1300, entity: 550 },
  /** ADR takes no tier multiplier. */
  adr: { doc: 5700, section: 2000, entity: 880 },
}

/** `sentences` is a count, not a length — it does not scale with the language. The rest are ×2.2. */
export const limits = { sentences: 4, title: 88, field: 440, ac: 220, logNote: 260 }

/** Does an ADR's consequences section name a cost? */
export const tradeoff = /trade-?off|cost|give[s]? up|sacrific|accept(s|ed)? (the )?(risk|limit|constraint)|in exchange|at the price of/i
/** Is a revisit condition only a deadline? */
export const deadlineOnly = /\d\s*(months?|weeks?|quarters?|years?|days?)|next quarter|periodic(ally)? review|revisit (in|after)/i

/** Text written to artifacts when the profile lang is en. */
export const written = {
  adrIndex: {
    title: 'Title', status: 'Status', legacy: 'legacy', heading: 'Decision log',
    comment: '<!-- Generated by adr-index.mjs. Do not edit manually; ADR files are the source of truth. -->',
    summary: (total, live, legacy) => `${total} decisions · ${live} active.${legacy ? ` ${legacy} legacy documents use H1 and header tables; add frontmatter to record scope.` : ''}`,
    live: 'Active decisions', past: 'Past decisions', empty: 'None yet.',
    history: 'Superseded, deprecated, or rejected decisions. IDs are never reused; these records explain earlier decisions and why they changed.',
  },
  result: { done: 'done', partial: 'partial', failed: 'failed' },
  divergence: 'differs from plan',
  none: 'none',
  noPr: 'no PR',
}
